apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca-cert
  namespace: csi-secrets
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBqDCCAU6gAwIBAgIRAMRt+Py63bj8yE/WYsLYjLcwCgYIKoZIzj0EAwIwMjET
    MBEGA1UEChMKSG9tZWxhYiBDQTEbMBkGA1UEAxMSSG9tZWxhYiBDQSBSb290IENB
    MB4XDTI2MDMxMjE1MDYwNloXDTM2MDMwOTE1MDYwNlowMjETMBEGA1UEChMKSG9t
    ZWxhYiBDQTEbMBkGA1UEAxMSSG9tZWxhYiBDQSBSb290IENBMFkwEwYHKoZIzj0C
    AQYIKoZIzj0DAQcDQgAEGXU58d5N+x0aXX9l3tC04RIbHnvXX5U7rJiodLpxKLrx
    WydCU0oFWr7AriWsCsRe/HUqrRNvQ9vdVZwoT898VKNFMEMwDgYDVR0PAQH/BAQD
    AgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFMr9weibkWmEmku9Hemt
    c/rnnMrtMAoGCCqGSM49BAMCA0gAMEUCIQCrfFpNgT1uWMryBPKYjD131IeXKS2r
    w4s4LoVW7imXWgIgdka3KiIRu1NTMzBTZ3bFK0xNtY8ozJyacRVnc+SEu7o=
    -----END CERTIFICATE-----
