apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - probe-vaultwarden.yaml
  - prometheusrule-vaultwarden.yaml
  - probe-homelab-apps.yaml
  - prometheusrule-homelab-apps.yaml
