apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: paperless-endpoint
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  interval: 60s
  module: http_401
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
        - https://docs.khoahuynh.dev/api/documents/
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: seafile-endpoint
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  interval: 60s
  module: http_2xx_pong
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
        - https://storage.khoahuynh.dev/api2/ping/
