apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: vaultwarden-endpoints
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
        - https://vault.khoahuynh.dev/alive
        - https://vault.khoahd.xyz/alive
